# dataset config : Sequential Recommendation
dataset: 'ML'
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
repeatable : True
RATING_FIELD: rating            # (str) Field name of rating feature.
LABEL_FIELD: rating
load_col: 
    inter: ['user_id', 'item_id', 'timestamp', 'rating'] 
    user: ['user_id']
    item: ['item_id', 'director', 'class', 'writer', 'release_year']